name: 'build and push to dockerhub and initiate deployment'
description: 'Build docker image, push it to dockerhub and initiate deployment'
inputs:
  image-name:
    description: 'The docker container image name'
    required: true
  docker-file:
    description: 'The dockerfile used by the docker build command'
    required: true
  deploy-action-repo:
    description: 'Deployment will be invoked on this repo after image push'
    required: true
  dockerhub-username:
    description: 'Dockerhub username'
    required: true
  dockerhub-password:
    description: 'Dockerhub password'
    required: true
  github-pat:
    description: 'Github personal access token to be used to call the deploy-action-repo'
    required: true
  npm-registry:
    description: 'NPM registry url'
    required: true
  npm-user:
    description: 'NPM registry username'
    required: true
  npm-pass:
    description: 'NPM registry pasword'
    required: true
  npm-email:
    description: 'NPM users email address'
    required: true
  github-ref: 
    descripiton: 'branch ref'
    required: true
  github-sha:
    required: true
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image-name }}
    - ${{ inputs.docker-file }}
    - ${{ inputs.dockerhub-username }}
    - ${{ inputs.dockerhub-password }}
    - ${{ inputs.github-pat }}
    - ${{ inputs.deploy-action-repo }}
    - ${{ imputs.github-ref }}
    - ${{ inputs.github-sha }}
    - ${{ inputs.npm-registry }}
    - ${{ inputs.npm-user }}
    - ${{ inputs.npm-pass }}
    - ${{ inputs.npm-email }}
    
